Parse user ranking position on slash commands
impulsoteam/atena pull request #21
Opened 2018-09-25 17:15 UTC by lazaroalvarenga

2018-09-25 20:44 UTC, ribeiroevandro approved these changes

2018-09-26 12:50 UTC, omarciovsena requested changes

2018-09-26 12:50 UTC, omarciovsena commented on controllers/user.js
> +export const rankingPosition = async userId => {
@lazaroalvarenga, I downloaded the branch and ran it locally. However, I had to add the `rankingPosition` function in the export default. If you do not I'm getting the following error:

`rankingPosition is not a function`

2018-09-26 12:51 UTC, omarciovsena approved these changes

2018-09-27 02:09 UTC, merged