Adding begin date and finish date pro
impulsoteam/atena pull request #448
Opened 2019-05-22 00:32 UTC by thaismartinsprojects

2019-06-04 16:03 UTC, goldblade approved these changes

2019-06-04 18:16 UTC, arthurazevedofranca commented on controllers/user.js
>  export const handlePro = async user => {
acho que pela mudanca de implementacao dessa funcao deveria mudar o nome da funcao tambem.
por exemplo, olhei a acima na linha 304 e 305 e tomei um susto
    user.score = newScore;
    user = await handlePro(user);
ta setando score no user e do nada pega um novo user? agora a funcao na vdd "seta" o pro no user e é responsavel por devolver o mesmo user passado. É bom centralizar essa logica mas tem que tomar cuidado com questoes como imutabilidade por exemplo e legibilidade pq senao pode induzir a outros erros com problema de referencia ao objeto

2019-06-04 18:38 UTC, arthurazevedofranca commented on controllers/user.js
>  export const handlePro = async user => {
Agora revendo vi que essa funcao, pro, datas ainda roda runPublisher

2019-06-04 19:34 UTC, arthurazevedofranca requested changes

2019-06-04 19:34 UTC, arthurazevedofranca commented on controllers/user.js
> +      user.proBeginAt = user.proBeginAt || data.current_plan.begin_at;
acho bom encapsular essa logica junto ao handlePro ou onde estejam a logica existente que ja seta as datas pro beginat e finishat

2019-06-04 19:34 UTC, arthurazevedofranca commented on utils/pro.js
> +export const isEligibleToPro = async user =>
revendo esse utils pro e o handle pro no controllers/user acho que podemos melhorar encapsulando todas as logicas de pro dentro do UserModel na classe com functions transients e centralizar toda essa logica nela

2019-06-17 14:05 UTC, cenicoemir commented
@thaismartinsprojects Sabe me dizer qual é o impeditivo de dar merge nessa? Me fugiu da memória totalmente.

2019-08-01 21:56 UTC, thaismartinsprojects commented
This PR was integrated on #475

2019-08-01 21:56 UTC, closed without merging