Chore/GitHub feedback
impulsoteam/atena pull request #468
Opened 2019-06-10 12:07 UTC by goldblade

2019-06-10 16:42 UTC, arthurazevedofranca requested changes
Vi muitos textos no codigo e acho que poderiamos centralizar em um arquivo com categoria e uma inducao doq se refere.
Nao terminei pq ficou mto extenso o PR, sugiro na proxima vez quebrar, nem que seja somente um PR com singlequote e por ai vai.
Se der depois eu reviso com calma os testes pq ja gastei muito tempo rs

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubController.js
> +// import interactionController from "../../controllers/interaction"
remover essa linha comentada

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubController.js
> +    .then(() => {
acho que aqui seria melhor o finally para ter certeza que sera chamado indiferenca do uso em cadeia acima
E seria mais funcional de fato fazer a passagem do response na cadeia de promessas do que inicia-la acima e usando as promises com sideeffects

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubController.js
> +      response.msg = `Olá! Leal, ${
como falei no comentario do finally, é ilegivel vc ter uma funcao que se tiver o githubId nao tem retorno mas se nao tiver ai sim retorna alg coisa e nesse caso um reject. Se fosse em outra estrutura e veria a necessidade de nao fazer side effect e ter uma leitura mais coesa dela

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubDAL.js
> +    return Promise.resolve(results.map(row => row.repositoryId))
precisa desse PRomise.resolve? ja esta dentro de um then sendo resolvido automaticamente para uma nova promessa

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubController.js
> +const addExcludedUser = async req => {
revendo as funcoes abaixo desse arquivo creio que as observacoes acima se aplicam, tanto sobre sideeffect/codigo funcional como uso de finally e promises

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubDAL.js
> +    return Promise.resolve(doc.excludedUsers)
aqui tambem precisa do promise resolve?

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubDAL.js
> +        return Promise.reject('Usuário não adicionado a lista de excluídos')
essa mensagem chega em algum lugar? pq pelo o que vi entra no catch seguido em funcao dela e retorna um false, nao seria melhor entao remover esse catch, fazer um log com essa mensagem e retornar false?

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubService.js
> +  switch (action) {
sendo um switch para retornar um valor acho melhor um uso de mapa, fica mais estruturado
ex:
const typesByAction = {
  'closed': 'merged_pull_request',
  'opened': 'pull_request'
}
return typesByAction[action]

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubController.js
> +        service.sendMessage(userModel)
outro caso de sideeffect, no caso se usar o bluebirdjs teriamos a implementacao .tap que faria bem mais sentido

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubService.js
> +  if (data.pull_request) type = defaultFunctions.getTypeByAction(data.action)
é essa ordem mesmo? entao o pullrequest sempre tera preferencia podendo sobrescrever os outros casos?
pq caso for poderia ser algo
return (data.pull_request && defaultFunctions.getTypeByAction(data.action))
 || (data.review && 'review)
 || (data.issue && 'issue')

em um unico fluxo, sem leitura induzindo a outros fluxos, ficando mais legivel

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubService.js
> +  let response = {}
aqui semelhante ao caso que citei acima, podemos fazer em uma unica linha sem 4 ifs

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/githubService.js
> +  let response = {}
Ou melhor, podemos fazer com um mapa tornando mais legivel, exemplo

const mapResponse = {
  'issue': data =>  defaultFunctions.normalizeIssue(data),
  'review': data =>  defaultFunctions.normalizeReview(data),
  'pull_request': data =>  defaultFunctions.normalizePullRequest(data),
  'merged_pull_request': data =>  defaultFunctions.normalizeMergedPullRequest(data),
}

const response = mapResponse[data.type](data)

2019-06-10 16:42 UTC, arthurazevedofranca commented on components/github/index.js
> +// import * as dal from "./githubDAL"
remover codigo comentado

2019-06-10 17:05 UTC, goldblade commented on components/github/githubController.js
> +// import interactionController from "../../controllers/interaction"
essa ideia de centralizar os textos, já tinha levantado esse ponto em calls com o time do atena. Até por que imagine que alguem queira personalizar o uso da aplicação para outro contexto.

2019-06-10 17:14 UTC, goldblade commented on components/github/githubController.js
> +    .then(() => {
tentei até usar o finnaly antes, mas recebi um warning nos testes se não me engano. não lembro exatamente o motivo, vou da uma olhada e exemplificar.

2019-06-10 17:15 UTC, goldblade commented on components/github/githubService.js
> +  switch (action) {
Bom ponto, vou refatorar

2019-06-10 17:23 UTC, goldblade commented on components/github/githubDAL.js
> +    return Promise.resolve(results.map(row => row.repositoryId))
nops, fixed

2019-06-10 17:26 UTC, goldblade commented on components/github/githubController.js
> +        service.sendMessage(userModel)
Ainda não lidei com o bluebirds a fundo. Vou da uma olhada nisso, obrigado :)

2019-06-10 17:26 UTC, goldblade commented on components/github/githubService.js
> +  let response = {}
Show. refatorando

2019-06-16 02:22 UTC, thaismartins approved these changes

2019-06-17 13:53 UTC, cenicoemir commented
@thaismartinsprojects @goldblade Vi que aprovaram, mas há alguns conflitos que o git está alertando, podem passar uma vista nisso?

2019-06-17 14:09 UTC, cenicoemir commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor do Github](https://trello.com/c/brbb5Xxy/108-refactor-do-github)

2019-07-04 18:44 UTC, merged