Solve it with a userController.findAll() param for isCoreTeam
impulsoteam/atena pull request #52
Opened 2018-10-05 22:00 UTC by lazaroalvarenga

2018-10-05 23:22 UTC, rtarantelli requested changes

2018-10-05 23:22 UTC, rtarantelli commented on controllers/user.js
> +  findCoreTeam
O find poderia receber um parâmetro isCoreTeam, assim não seria necessário o método findCoreTeam

2018-10-06 00:02 UTC, lazaroalvarenga commented
@rtarantelli ✅

2018-10-06 00:17 UTC, rtarantelli approved these changes

2018-10-08 13:42 UTC, merged