Send a Hello message on Slack after create user on your first interaction
impulsoteam/atena pull request #53
Opened 2018-10-05 22:39 UTC by lazaroalvarenga

#44

2018-10-05 23:42 UTC, rtarantelli requested changes

2018-10-05 23:42 UTC, rtarantelli commented on utils/bot.js
> +    console.log(response);
Não é uma boa prática deixar console.log :-/

2018-10-05 23:53 UTC, lazaroalvarenga commented
@rtarantelli ✅

2018-10-06 00:21 UTC, rtarantelli approved these changes

2018-10-08 13:50 UTC, merged