feat: remove user
impulsoteam/atena pull request #592
Opened 2019-10-07 14:43 UTC by thejullius

- Usuário e todos os seus dados serão completamente removidos quando vim `status: archived` do next;

2019-10-07 19:23 UTC, andrecavallari requested changes

2019-10-07 19:23 UTC, andrecavallari commented on components/users/usersController.js
> +    return JSON.stringify(error)
O try/catch não dá return, ele "trava" a execução desse contexto, então aqui o correto seria:
```suggestion
    errors._throw(file, 'removeUser', error)
```

2019-10-07 19:23 UTC, andrecavallari commented on components/users/usersController.js
> +const remove = async ({ uuid }) => {
```suggestion
const removeUser = async ({ uuid }) => {
```

2019-10-07 19:23 UTC, andrecavallari commented on components/next/nextController.js
> +      const success = await users.remove(data)
```suggestion
      const success = await users.removeUser(data)
```

2019-10-07 19:23 UTC, andrecavallari commented on components/next/nextController.js
> +      const success = await users.remove(data)
Na verdade mesmo, eu estava vendo aqui, nem precisa do await, vc pode dar um retorn users.removeUser(data) direto, o arquivo que consome essa informação na verdade já utiliza o await, porém nem está assimilando uma variável para a resposta dessa função, mas só mesmo por garantia pode deixar direto:
```suggestion
      return users.remove(data)
```

2019-10-07 19:23 UTC, andrecavallari commented on components/users/usersController.js
> +    const user = await UsersModel.deleteOne({ uuid })
```suggestion
    const user = await UsersModel.deleteOne({ uuid })
    const [interactions, logins, history, user] = Promise.all([
      InteractionsModel.deleteMany({ user: _id }),
      LoginsModel.deleteMany({ user: _id }),
      UsersLevelsHistoryModel.deleteMany({ user: _id }),
      UsersModel.deleteOne({ uuid })
    ])
```

2019-10-07 19:23 UTC, andrecavallari commented on components/users/usersController.js
> +    const user = await UsersModel.deleteOne({ uuid })
Mas pra ser bem sincero, eu ainda preferia fazer isso direto na model usando os hooks...

No arquivo 
```
const Interaction = mongoose.model('Interaction')
const Login = mongoose.model('Login')
const UserLevelHistory = mongoose.model('UserLevelHistory')

userSchema.pre('delete', async function(){
  await Promise.all([
    InteractionsModel.deleteMany({ user: this.deletedId })
    LoginsModel.deleteMany({ user: this.deletedId })
    UserLevelHistory.deleteMany({ user: this.deletedId })
  ])
})
```

2019-10-22 13:07 UTC, andrecavallari requested changes

2019-10-22 13:07 UTC, andrecavallari commented on components/users/user.js
> +  }
Nesses casos, dê preferência ao Promise.all, já que cada model não tem uma necessidade do resultado da outra.

```
userSchema.post('remove', async function() {
  try {
    await Promise.all([
      mongoose.model('Achievement').deleteMany({ user: this._id }),
      mongoose.model('AchievementLevel').deleteMany({ user: this._id }),
      mongoose.model('Interaction').deleteMany({ user: this._id }),
      mongoose.model('Login').deleteMany({ user: this._id }),
      mongoose.model('UserLevelHistory').deleteMany({ user: this._id })
    ])
  } catch(error) {
    errors._throw('User Schema', 'removeUser', error)
  }
})
```

2019-10-22 13:07 UTC, andrecavallari commented on components/next/nextController.js
> +  }
Eu sugeri a substituição do nome do método pra removeUserByUuid, pois o método exclui pelo uuid, e passa direto o data.uuid, fica mais compreensível, e passando direto o uuid ao invés de o objeto todo o método fica mais compatível com qualquer ocasião.

A sugestão dada aqui é para reduzir o número de linhas, se preferir ainda pode usar o try/catch que ainda estará correto, só o return mesmo está redundante, pois se em qualquer um dos dois casos vai usar o return você pode jogar apenas UM return pra fora do try/catch, antes de finalizar o bloco do `if (data.status === 'archived')`
```
if (data.status === 'archived') {
  return users.removeUserByUuid(data.uuid).catch(error => {
    errors._throw(file, 'handleUser', error)
  })
}
```

2019-10-22 13:07 UTC, andrecavallari commented on components/users/usersController.js
> +}
O ideal para se chamar uma instância da model em uma variável é sempre fora da função, diretamente no arquivo, portanto onde chama o `mongoose.model('User')` para atribuir a uma variável, o ideal é que seja feito FORA do método, de preferência nas primeiras linhas do arquivo, se é só esse caso de uso, você também pode chamar direto `mongoose.model('User').findOne({ uuid })`.

Uma vez que estamos excluindo o usuário pelo seu uuid, o ideal é que o nome do método diga exatamente o que ele faz, portanto sugiro que o nome desse método seja `removeUserByUuid`, por mais que fique um pouco maior, a compreensão do método fica melhor, outra sugestão é não usar o destructuring como parâmetro da função, pois se houver a necessidade de utilizar este método futuramente em outra ocasião já está preparado, então a sugestão é substituir o `async ({ uuid })` por apenas `async uuid`.

Outro detalhe, é o uso do `return await`. O await só deve ser utilizado em casos onde no mesmo método você irá precisar do resultado da promise ainda, caso contrário você pode retornar DIRETAMENTE a promise, os casos de `return await` são redundantes, seria o mesmo que chamar `promise.then(response => response)`.

```
const UserModel = mongoose.model('User')
const removeUserByUuid = async uuid => {
  try {
    const user = await UserModel.findOne({ uuid })
    return user.remove()
  } catch (error) {
    errors._throw(file, 'removeUserByUuid', error)
  }
}
```

2019-10-22 13:32 UTC, thejullius commented on components/users/usersController.js
> +}
Preciso do await nesse caso pois senao vou retornar pro nextController uma promisse pendente, que podem ser bem sucedida ou gerar erro.

2019-10-22 13:45 UTC, andrecavallari commented on components/users/usersController.js
> +}
Mesmo com o await, você ainda estará retornando uma promise, que ainda pode ser bem sucedida ou gerar um erro... o await é o mesmo que colocar um .then() no final

2019-10-22 13:53 UTC, andrecavallari approved these changes

2019-10-24 17:09 UTC, merged