multiple users
impulsoteam/atena pull request #625
Opened 2019-12-10 13:25 UTC by thejullius

- Command `!darpontos` now accepts multiple users;

2019-12-10 13:41 UTC, andrecavallari requested changes

2019-12-10 13:41 UTC, andrecavallari commented on components/commands/commandsUtils.js
> +      text: `Digite ${'`!darpontos`'} ${'`@lista @usuários`'} ${'`pontos`'} ${'`motivo`'} para dar pontos de reputação ao usuário. `
```suggestion
      text: `Digite \`!darpontos\` \`@lista @usuários\` \`pontos\` \`motivo\` para dar pontos de reputação ao usuário. `
```

2019-12-10 18:29 UTC, andrecavallari approved these changes

2019-12-11 17:36 UTC, omarciovsena approved these changes

2019-12-11 17:37 UTC, merged