Chore: remove rocketchat
impulsoteam/atena pull request #754
Opened 2021-08-13 12:47 UTC by marianaviana

2021-08-13 15:07 UTC, goldblade commented
Não vai mais ter integração com o rocket.chat? Mudou a plataforma ?

2021-08-13 16:12 UTC, marciovsena commented on src/config/achievements/index.js
> -    rocketchat: 'rocketchat'
@marianaviana atuar apenas nessa função já desabilitaria o rockechat. Podemos manter os eventos de chatAccess, messageSended..., pois iremos simplesmente adicionar novos providers. O que acha?

2021-08-17 18:29 UTC, thejullius commented on src/config/achievements/index.js
> +/* export const messageProviders = provider => {
Fazer com que aqui retorne null e todas as funções devem verificar se tem provider antes de proseguir

2021-08-17 18:30 UTC, thejullius commented on src/controllers/AchievementController.js
>        BotController.sendMessageToUser({
Nao executar essa linha se nao tiver provider

2021-08-17 18:30 UTC, thejullius commented on src/controllers/AchievementController.js
>        BotController.sendMessageToUser({
157

2021-08-17 18:34 UTC, thejullius commented on src/controllers/CommandController/utils.js
> +// import BotController from '../BotController'
Pode deixar todo esse codigo.

2021-08-17 19:18 UTC, marciovsena requested changes

2021-08-17 19:18 UTC, marciovsena commented on src/controllers/AchievementController.js
> +      }
```suggestion
      const providerOrDefault = messageProviders(provider)
      if (providerOrDefault) {
        BotController.sendMessageToUser({
          provider: providerOrDefault,
          message,
          username: user[providerOrDefault].username
        })
      }
```

2021-08-17 19:18 UTC, marciovsena commented on src/controllers/CommandController/utils.js
> +    if (!provider) {
@marianaviana só podemos executar se for diferente de null, então é o contrário
```suggestion
    if (provider) {
```

2021-08-17 19:18 UTC, marciovsena commented on src/controllers/CommandController/utils.js
> +      if (!provider) {
```suggestion
      if (provider) {
```

2021-08-17 19:18 UTC, marciovsena commented on src/controllers/LevelController.js
> +      if (user.level.value > previousLevel && providers.length > 0) {
```suggestion
      if (user.level.value > previousLevel) {
```

@marianaviana acredito que você não precisa dessa condição, pois na linha 28 um array vazio simplesmente não terá loop

2021-08-17 19:18 UTC, marciovsena commented on src/controllers/ScoreController/index.js
> +          }
```suggestion
         const providerOrDefault = messageProviders(provider)
          if (providerOrDefault) {
            BotController.sendMessageToUser({
              provider: providerOrDefault,
              message,
              username: user[providerOrDefault].username
            })
          }
```

2021-08-17 19:37 UTC, marciovsena approved these changes

2021-08-17 19:52 UTC, thejullius approved these changes

2021-08-30 20:35 UTC, merged